name : Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: "epitechcontent/epitest-docker:devel"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make re

      - name: Ensure binary is present a the root
        run: |
          if [ ! -f ./myftp ]; then
            echo "epitest binary not found"
            exit 1
          fi